.TH "logo-generator" 1 "01 June 2016" "v2.0.1" 

.SH NAME 
The Christoffen Corporation Logo Generator v2.0.1
.SH SYNOPSIS
Generates three versions of the Christoffen logo
.SH DESCRIPTION
There are multiple options that will be able to be used below. The logo generator can be summoned using the "logo-generator" command after running "make && make install." After this, you can generate the three formats, or specify just one, all, part of one, or what the options below will allow.
.SH OPTIONS
Usage: logo-generator [OPTION...]

  -a, --all-images           Generate all images: Outlines, Colors, and Logos.

  -c, --colored-all          Generate all colored triangles, and the logo

  -C, --colored-no-logo      Generate all colored triangles, except for the
                             logo

  -F, --frankenlogos         Generate the Frankenlogos (don't ask; just do)

  -o, --outlined-all         Generate all outlined triangles, and the logo

  -O, --outlined-no-logo     Generate all outlined triangles, except for the
                             logo

  -?, --help                 Give this help list
      --usage                Give a short usage message
  -V, --version              Print program version

.SH BUGS
Report bugs to M. Gage Morgan <gage@christoffen.com>.
.SH AUTHOR
M. Gage Morgan <gage@christoffen.com>
.SH SEE ALSO
libcairo2 development headers - dependency

